package innoLessons.lab11.exercise2;

public class Bill {
    private final int billId;
    private final String name;
    private final double amount;
    private final int patientId; // Each bill belongs to a patient
    private final int receptionistId; // Bill generated by a receptionist

    public Bill(int billId, String name, double amount, int patientId, int receptionistId) {
        this.billId = billId;
        this.name = name;
        this.amount = amount;
        this.patientId = patientId;
        this.receptionistId = receptionistId;
    }

    public int getBillId() {
        return billId;
    }

    public double getAmount() {
        return amount;
    }

    public int getPatientId() {
        return patientId;
    }

    @Override
    public String toString() {
        return "Bill ID: " + billId + ", Name: " + name + ", Amount: $" + amount;
    }
}
